### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by buker** [Papy-3D-Factory/Klipper-Artillery_Sidewinder_X2#1]
Hi, Could you keep documentation in English? It will be easier to understand your configuration

**Comment by Papy-3D-Factory** [comment]
That's a good suggestion, it's not my priority, but as soon as I have some free time I'll take care of it

**Comment by Papy-3D-Factory** [comment]
The English translation is done and available for the PDF files of the tutorials.... Enjoy
